[project]
name = "shelfie-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Miguel Cazorla Zamora", email = "miguelzamora210405@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beanie>=2.2.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
    "uvicorn[standard]>=0.52.4",
]

[tool.uv]
package = false
